import DashboardPageHeader from "@/components/ui/custom/dashboard-page-header";
import DashboardPageLayout from "@/components/ui/custom/dashboard-page-layout";
import { DataTable } from "@/components/ui/custom/data-table";
import { columns } from "@/components/ai-shopping/columns";
import { ShoppingCart, Sparkles, Info, AlertCircle } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getActiveMessIdFromCookies } from "@/services/auth.service";
import { getAiShoppingLists } from "@/services/ai-shopping.service";

export default async function MemberAiShoppingPage() {
  const activeMessId = await getActiveMessIdFromCookies();

  if (!activeMessId) {
    return (
      <DashboardPageLayout>
        <div className="flex flex-col items-center justify-center min-h-100 space-y-4 text-center">
          <AlertCircle className="h-10 w-10 text-muted-foreground opacity-20" />
          <h2 className="text-lg font-bold">No Active Mess</h2>
          <p className="text-sm text-muted-foreground">Select a mess to view AI shopping lists.</p>
        </div>
      </DashboardPageLayout>
    );
  }

  const response = await getAiShoppingLists(activeMessId, { limit: "100" });
  const visibleLists = (response.data || []).filter((list) => list.status === "approved" || list.status === "converted");

  return (
    <DashboardPageLayout>
      <DashboardPageHeader
        title="AI Shopping Lists"
        description="View approved market lists generated by our AI assistant based on menu plans."
      />

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <Card className="lg:col-span-3">
          <CardHeader>
            <CardTitle className="text-sm font-bold flex items-center gap-3">
              <ShoppingCart className="h-4 w-4 text-primary" />
              Approved Market Lists
            </CardTitle>
          </CardHeader>
          <CardContent>
            <DataTable columns={columns} data={visibleLists} />
          </CardContent>
        </Card>

        <div className="space-y-4">
          <Card className="bg-primary/5 border-primary/20">
            <CardHeader>
              <CardTitle className="text-sm font-bold flex items-center gap-3 text-primary">
                <Sparkles className="h-4 w-4" />
                AI Assistant
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground leading-relaxed">
                These lists are automatically generated from published menu plans and manager review.
              </p>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader>
              <CardTitle className="text-sm font-bold flex items-center gap-3">
                <Info className="h-4 w-4 text-primary" />
                Member Access
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground leading-relaxed">
                As a member, you can view approved or converted lists. Generation and approval are restricted to managers.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </DashboardPageLayout>
  );
}