"use client";

import DashboardHeader from "@/components/ui/custom/page-header";
import DashboardPageLayout from "@/components/ui/custom/dashboard-page-layout";
import { DataTable } from "@/components/ui/custom/data-table";
import { columns } from "@/components/ai-shopping/columns";
import { mockAiLists } from "@/components/ai-shopping/mockData";
import { 
  ShoppingCart, 
  Sparkles,
  Info
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function MemberAiShoppingPage() {
  // Members only see approved/converted lists for reference
  const visibleLists = mockAiLists.filter(l => l.status === "approved" || l.status === "converted");

  return (
    <DashboardPageLayout>
      <DashboardHeader
        title="AI Shopping Lists"
        description="View approved market lists generated by our AI assistant based on menu plans."
      />

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <Card className="lg:col-span-3">
          <CardHeader>
            <CardTitle className="text-sm font-bold flex items-center gap-2">
              <ShoppingCart className="h-4 w-4 text-primary" />
              Approved Market Lists
            </CardTitle>
          </CardHeader>
          <CardContent>
            <DataTable columns={columns} data={visibleLists} />
          </CardContent>
        </Card>

        <div className="space-y-4">
          <Card className="bg-primary/5 border-primary/20">
            <CardHeader>
              <CardTitle className="text-sm font-bold flex items-center gap-2 text-primary">
                <Sparkles className="h-4 w-4" />
                AI Assistant
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground leading-relaxed">
                These lists are automatically generated by analyzing nutrient requirements and market price trends for the published menu plans.
              </p>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader>
              <CardTitle className="text-sm font-bold flex items-center gap-2">
                <Info className="h-4 w-4 text-primary" />
                Member Access
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-muted-foreground leading-relaxed">
                As a member, you can view the approved lists to prepare for market duties. Generation and approval are restricted to managers.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </DashboardPageLayout>
  );
}
